version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: jobtrackkerdb
      TZ: "Asia/Bangkok" # Set timezone to Thailand
    ports:
      - "5432:5432"
    volumes:
      - D:/Programer_eieiza/ProjectWork/PERSONAL_PROJECT/WEBAPPJOBTRACKER/storage/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exampleuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    environment:
      TZ: "Asia/Bangkok" # Set timezone to Thailand
    ports:
      - "6379:6379"
    volumes:
      - D:/Programer_eieiza/ProjectWork/PERSONAL_PROJECT/WEBAPPJOBTRACKER/storage/redis:/data

  jobtracker-api:
    image: go-api-jobtrackker:latest # Use the existing image if available
    build:
      context: ../jobstracker-api/.
      dockerfile: Dockerfile
    container_name: goapp
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRESQL_CONNECTION_STRING: postgres://exampleuser:examplepassword@postgres:5432/jobtrackkerdb?sslmode=disable
      JOBSURL: https://th.jobsdb.com/api/chalice-search/v4/search
      PYTHONSERVERPATH : http://localhost:8000
      # JOBS_WORKER_TRIGGER_TIME: 30
      TZ: "Asia/Bangkok" # Set timezone to Thailand

volumes:
  postgres_data:
  redis_data: